<template>
  <div v-if="open" class="tr-modal-overlay" @click.self="emit('close')">
    <div class="tr-modal">
      <div class="tr-modal-header">
        <div class="tr-modal-title">
          {{ mode === 'create' ? 'Add Trigger' : 'Edit Trigger' }}
        </div>
        <button class="tr-icon-btn" type="button" title="Close" @click="emit('close')">
          <svg viewBox="0 0 20 20" width="18" height="18">
            <path
              fill="currentColor"
              d="M6.28 5.22a.75.75 0 00-1.06 1.06L8.94 10l-3.72 3.72a.75.75 0 101.06 1.06L10 11.06l3.72 3.72a.75.75 0 101.06-1.06L11.06 10l3.72-3.72a.75.75 0 00-1.06-1.06L10 8.94 6.28 5.22z"
            />
          </svg>
        </button>
      </div>

      <div class="tr-modal-body">
        <div v-if="localError || error" class="tr-alert tr-alert-danger">
          {{ localError || error }}
        </div>

        <div v-if="isNodeManaged" class="tr-alert tr-alert-warn">
          <div class="tr-alert-title">Managed trigger</div>
          <div class="tr-alert-text">
            This trigger is generated by a Trigger node in the workflow. Edit it in Builder.
          </div>
          <button
            class="tr-btn tr-btn-ghost"
            type="button"
            :disabled="saving"
            @click="emit('open-builder', form.flowId)"
          >
            Open Builder
          </button>
        </div>

        <div class="tr-grid">
          <div class="tr-field">
            <label class="tr-label">Workflow</label>
            <select
              v-model="form.flowId"
              class="tr-select"
              :disabled="mode === 'edit' || saving || isNodeManaged"
            >
              <option value="" disabled>Select a workflow</option>
              <option v-for="f in flows" :key="f.id" :value="f.id">
                {{ f.name || f.id }}
              </option>
            </select>
          </div>

          <div class="tr-field">
            <label class="tr-label">Type</label>
            <select
              v-model="form.kind"
              class="tr-select"
              :disabled="mode === 'edit' || saving || isNodeManaged"
            >
              <option value="manual">manual</option>
              <option value="interval">interval</option>
              <option value="once">once</option>
              <option value="url">url</option>
              <option value="cron">cron</option>
              <option value="command">command</option>
              <option value="contextMenu">contextMenu</option>
              <option value="dom">dom</option>
            </select>
          </div>
        </div>

        <div class="tr-field tr-field-inline">
          <label class="tr-checkbox">
            <input
              v-model="form.enabled"
              type="checkbox"
              :disabled="saving || isNodeManaged"
              class="tr-checkbox-input"
            />
            <span>Enabled</span>
          </label>
        </div>

        <div v-if="mode === 'edit'" class="tr-field">
          <label class="tr-label">Trigger ID</label>
          <input class="tr-input" :value="form.id || ''" disabled />
        </div>

        <!-- Kind-specific fields -->
        <div v-if="form.kind === 'interval'" class="tr-field">
          <label class="tr-label">Interval (minutes)</label>
          <input
            v-model.number="form.periodMinutes"
            class="tr-input"
            type="number"
            min="1"
            step="1"
            :disabled="saving || isNodeManaged"
          />
          <div class="tr-hint">Repeats via chrome.alarms.periodInMinutes.</div>
        </div>

        <div v-else-if="form.kind === 'once'" class="tr-field">
          <label class="tr-label">Trigger time</label>
          <input
            v-model="form.whenLocal"
            class="tr-input"
            type="datetime-local"
            :disabled="saving || isNodeManaged"
          />
          <div class="tr-hint">Will auto-disable after firing. Local timezone.</div>
        </div>

        <div v-else-if="form.kind === 'url'" class="tr-field">
          <label class="tr-label">URL match rules</label>
          <div class="tr-list">
            <div v-for="(r, i) in form.urlMatch" :key="i" class="tr-list-row">
              <select
                v-model="r.kind"
                class="tr-select tr-select-sm"
                :disabled="saving || isNodeManaged"
              >
                <option value="url">url (prefix)</option>
                <option value="domain">domain (contains)</option>
                <option value="path">path (prefix)</option>
              </select>
              <input
                v-model="r.value"
                class="tr-input tr-input-sm"
                type="text"
                placeholder="https://example.com/app"
                :disabled="saving || isNodeManaged"
              />
              <button
                class="tr-btn tr-btn-icon"
                type="button"
                title="Move up"
                :disabled="saving || isNodeManaged || i === 0"
                @click="move(form.urlMatch, i, -1)"
              >
                ↑
              </button>
              <button
                class="tr-btn tr-btn-icon"
                type="button"
                title="Move down"
                :disabled="saving || isNodeManaged || i === form.urlMatch.length - 1"
                @click="move(form.urlMatch, i, 1)"
              >
                ↓
              </button>
              <button
                class="tr-btn tr-btn-icon tr-btn-danger"
                type="button"
                title="Remove"
                :disabled="saving || isNodeManaged"
                @click="form.urlMatch.splice(i, 1)"
              >
                ×
              </button>
            </div>
          </div>
          <button
            class="tr-btn tr-btn-ghost"
            type="button"
            :disabled="saving || isNodeManaged"
            @click="form.urlMatch.push({ kind: 'url', value: '' })"
          >
            + Add rule
          </button>
        </div>

        <div v-else-if="form.kind === 'cron'" class="tr-grid">
          <div class="tr-field">
            <label class="tr-label">Cron</label>
            <input
              v-model="form.cron"
              class="tr-input"
              type="text"
              placeholder="0 9 * * *"
              :disabled="saving || isNodeManaged"
            />
          </div>
          <div class="tr-field">
            <label class="tr-label">Timezone (optional)</label>
            <input
              v-model="form.timezone"
              class="tr-input"
              type="text"
              placeholder="America/Los_Angeles"
              :disabled="saving || isNodeManaged"
            />
          </div>
        </div>

        <div v-else-if="form.kind === 'command'" class="tr-field">
          <label class="tr-label">Command key</label>
          <input
            v-model="form.commandKey"
            class="tr-input"
            type="text"
            placeholder="run_quick_trigger_1"
            :disabled="saving || isNodeManaged"
          />
          <div class="tr-hint">
            Command triggers must be declared in the extension manifest and cannot be added at
            runtime.
          </div>
        </div>

        <div v-else-if="form.kind === 'contextMenu'" class="tr-field">
          <label class="tr-label">Menu title</label>
          <input
            v-model="form.contextMenuTitle"
            class="tr-input"
            type="text"
            placeholder="Run workflow"
            :disabled="saving || isNodeManaged"
          />

          <label class="tr-label tr-label-spaced">Contexts</label>
          <div class="tr-checkbox-grid">
            <label v-for="c in menuContexts" :key="c" class="tr-checkbox">
              <input
                v-model="form.contextMenuContexts"
                type="checkbox"
                :value="c"
                :disabled="saving || isNodeManaged"
                class="tr-checkbox-input"
              />
              <span>{{ c }}</span>
            </label>
          </div>
        </div>

        <div v-else-if="form.kind === 'dom'" class="tr-field">
          <label class="tr-label">Selector</label>
          <input
            v-model="form.domSelector"
            class="tr-input"
            type="text"
            placeholder="#app .item"
            :disabled="saving || isNodeManaged"
          />

          <div class="tr-grid">
            <div class="tr-field tr-field-inline">
              <label class="tr-checkbox">
                <input
                  v-model="form.domAppear"
                  type="checkbox"
                  :disabled="saving || isNodeManaged"
                  class="tr-checkbox-input"
                />
                <span>Fire when appears</span>
              </label>
            </div>
            <div class="tr-field tr-field-inline">
              <label class="tr-checkbox">
                <input
                  v-model="form.domOnce"
                  type="checkbox"
                  :disabled="saving || isNodeManaged"
                  class="tr-checkbox-input"
                />
                <span>Once</span>
              </label>
            </div>
          </div>

          <div class="tr-field">
            <label class="tr-label">Debounce (ms)</label>
            <input
              v-model.number="form.domDebounceMs"
              class="tr-input"
              type="number"
              min="0"
              step="50"
              :disabled="saving || isNodeManaged"
            />
          </div>
        </div>

        <div class="tr-field">
          <label class="tr-label">Args (JSON, optional)</label>
          <textarea
            v-model="form.argsText"
            class="tr-textarea"
            rows="4"
            placeholder='{\n  "foo": "bar"\n}'
            :disabled="saving || isNodeManaged"
          ></textarea>
          <div class="tr-hint">Passed as trigger args and merged into flow vars for the run.</div>
        </div>
      </div>

      <div class="tr-modal-footer">
        <button class="tr-btn tr-btn-ghost" type="button" :disabled="saving" @click="emit('close')">
          Cancel
        </button>
        <button
          class="tr-btn tr-btn-primary"
          type="button"
          :disabled="saving || isNodeManaged || !canSubmit"
          @click="submit"
        >
          {{ saving ? 'Saving…' : 'Save' }}
        </button>
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { computed, reactive, ref, watch } from 'vue';

import type {
  TriggerSpec,
  UrlMatchRule,
} from '@/entrypoints/background/record-replay-v3/domain/triggers';

interface FlowLite {
  id: string;
  name: string;
}

type TriggerSpecCreate = Omit<TriggerSpec, 'id'> & { id?: string };

const props = defineProps<{
  open: boolean;
  mode: 'create' | 'edit';
  flows: FlowLite[];
  trigger?: TriggerSpec | null;
  saving?: boolean;
  error?: string | null;
  defaultUrl?: string;
}>();

const emit = defineEmits<{
  (e: 'close'): void;
  (
    e: 'submit',
    payload:
      | { mode: 'create'; trigger: TriggerSpecCreate }
      | { mode: 'edit'; trigger: TriggerSpec },
  ): void;
  (e: 'open-builder', flowId: string): void;
}>();

const saving = computed(() => props.saving === true);

const menuContexts = ['all', 'page', 'selection', 'image', 'link', 'video', 'audio'] as const;

function unixMsToDatetimeLocal(ms: number): string {
  const d = new Date(ms);
  const pad = (n: number) => String(n).padStart(2, '0');
  const year = d.getFullYear();
  const month = pad(d.getMonth() + 1);
  const day = pad(d.getDate());
  const hour = pad(d.getHours());
  const minute = pad(d.getMinutes());
  return `${year}-${month}-${day}T${hour}:${minute}`;
}

function datetimeLocalToUnixMs(value: string): number | null {
  if (!value || typeof value !== 'string') return null;
  const match = value.match(/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2})(?::(\d{2}))?$/);
  if (!match) return null;

  const [, yearStr, monthStr, dayStr, hourStr, minuteStr, secondStr] = match;
  const d = new Date(
    Number(yearStr),
    Number(monthStr) - 1,
    Number(dayStr),
    Number(hourStr),
    Number(minuteStr),
    Number(secondStr || 0),
    0,
  );
  const ms = d.getTime();
  return Number.isFinite(ms) ? ms : null;
}

function move<T>(arr: T[], i: number, d: number): void {
  const j = i + d;
  if (j < 0 || j >= arr.length) return;
  const tmp = arr[i];
  arr[i] = arr[j];
  arr[j] = tmp;
}

const form = reactive({
  id: '' as string,
  kind: 'interval' as TriggerSpec['kind'],
  flowId: '' as string,
  enabled: true,

  // Kind-specific
  periodMinutes: 5,
  whenLocal: unixMsToDatetimeLocal(Date.now() + 5 * 60 * 1000),
  urlMatch: [] as UrlMatchRule[],
  cron: '',
  timezone: '',
  commandKey: '',
  contextMenuTitle: 'Run workflow',
  contextMenuContexts: ['all'] as string[],
  domSelector: '',
  domAppear: true,
  domOnce: true,
  domDebounceMs: 800,

  // Common optional field
  argsText: '',
});

const localError = ref<string | null>(null);

const isNodeManaged = computed(() => {
  if (props.mode !== 'edit') return false;
  const trigger = props.trigger;
  if (!trigger) return false;
  const flowId = String(trigger.flowId || '');
  const trigPrefix = `trg_${flowId}_`;
  const schPrefix = `sch_${flowId}_`;
  return trigger.id.startsWith(trigPrefix) || trigger.id.startsWith(schPrefix);
});

function resetForCreate(): void {
  form.id = '';
  form.kind = 'interval';
  form.flowId = props.flows[0]?.id ?? '';
  form.enabled = true;

  form.periodMinutes = 5;
  form.whenLocal = unixMsToDatetimeLocal(Date.now() + 5 * 60 * 1000);
  form.urlMatch = [{ kind: 'url', value: props.defaultUrl ?? '' }];
  form.cron = '';
  form.timezone = '';
  form.commandKey = '';
  form.contextMenuTitle = 'Run workflow';
  form.contextMenuContexts = ['all'];
  form.domSelector = '';
  form.domAppear = true;
  form.domOnce = true;
  form.domDebounceMs = 800;

  form.argsText = '';
  localError.value = null;
}

function resetForEdit(trigger: TriggerSpec): void {
  form.id = trigger.id;
  form.kind = trigger.kind;
  form.flowId = trigger.flowId;
  form.enabled = !!trigger.enabled;

  form.periodMinutes = trigger.kind === 'interval' ? Number(trigger.periodMinutes) || 1 : 5;
  form.whenLocal =
    trigger.kind === 'once'
      ? unixMsToDatetimeLocal(Number(trigger.whenMs))
      : unixMsToDatetimeLocal(Date.now() + 5 * 60 * 1000);
  form.urlMatch = trigger.kind === 'url' ? [...(trigger.match || [])] : [];
  form.cron = trigger.kind === 'cron' ? String(trigger.cron || '') : '';
  form.timezone = trigger.kind === 'cron' ? String(trigger.timezone || '') : '';
  form.commandKey = trigger.kind === 'command' ? String(trigger.commandKey || '') : '';
  form.contextMenuTitle =
    trigger.kind === 'contextMenu' ? String(trigger.title || '') : 'Run workflow';
  form.contextMenuContexts =
    trigger.kind === 'contextMenu' ? [...(trigger.contexts || ['all'])] : ['all'];
  form.domSelector = trigger.kind === 'dom' ? String(trigger.selector || '') : '';
  form.domAppear = trigger.kind === 'dom' ? trigger.appear !== false : true;
  form.domOnce = trigger.kind === 'dom' ? trigger.once !== false : true;
  form.domDebounceMs = trigger.kind === 'dom' ? Number(trigger.debounceMs ?? 800) : 800;

  form.argsText = trigger.args ? JSON.stringify(trigger.args, null, 2) : '';
  localError.value = null;
}

watch(
  () => [props.open, props.mode, props.trigger] as const,
  () => {
    if (!props.open) return;

    if (props.mode === 'create') {
      resetForCreate();
      return;
    }
    if (props.trigger) {
      resetForEdit(props.trigger);
      return;
    }
    resetForCreate();
  },
  { immediate: true },
);

const canSubmit = computed(() => {
  if (!form.flowId.trim()) return false;
  if (localError.value) return false;
  if (form.kind === 'interval')
    return Number.isFinite(form.periodMinutes) && form.periodMinutes >= 1;
  if (form.kind === 'once') return !!datetimeLocalToUnixMs(form.whenLocal);
  if (form.kind === 'url') return form.urlMatch.some((r) => String(r.value || '').trim());
  if (form.kind === 'cron') return !!form.cron.trim();
  if (form.kind === 'command') return !!form.commandKey.trim();
  if (form.kind === 'contextMenu') return !!form.contextMenuTitle.trim();
  if (form.kind === 'dom') return !!form.domSelector.trim();
  return true;
});

function parseArgs(): Record<string, unknown> | undefined {
  const text = (form.argsText || '').trim();
  if (!text) return undefined;
  try {
    const parsed = JSON.parse(text) as unknown;
    if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
      localError.value = 'Args must be a JSON object.';
      return undefined;
    }
    return parsed as Record<string, unknown>;
  } catch (e) {
    localError.value = e instanceof Error ? e.message : 'Invalid JSON in args.';
    return undefined;
  }
}

function buildTrigger():
  | { mode: 'create'; trigger: TriggerSpecCreate }
  | { mode: 'edit'; trigger: TriggerSpec } {
  const args = parseArgs();
  const base = {
    id: form.id || undefined,
    kind: form.kind,
    enabled: !!form.enabled,
    flowId: form.flowId,
    args,
  };

  switch (form.kind) {
    case 'manual':
      return props.mode === 'create'
        ? { mode: 'create', trigger: base as TriggerSpecCreate }
        : { mode: 'edit', trigger: base as TriggerSpec };
    case 'interval': {
      const trigger = { ...base, periodMinutes: Math.max(1, Math.floor(form.periodMinutes)) };
      return props.mode === 'create'
        ? { mode: 'create', trigger: trigger as TriggerSpecCreate }
        : { mode: 'edit', trigger: trigger as TriggerSpec };
    }
    case 'once': {
      const whenMs = datetimeLocalToUnixMs(form.whenLocal);
      const trigger = { ...base, whenMs: whenMs ?? Date.now() };
      return props.mode === 'create'
        ? { mode: 'create', trigger: trigger as TriggerSpecCreate }
        : { mode: 'edit', trigger: trigger as TriggerSpec };
    }
    case 'url': {
      const match = form.urlMatch
        .map((r) => ({ kind: r.kind, value: String(r.value || '').trim() }))
        .filter((r) => r.value);
      const trigger = { ...base, match };
      return props.mode === 'create'
        ? { mode: 'create', trigger: trigger as TriggerSpecCreate }
        : { mode: 'edit', trigger: trigger as TriggerSpec };
    }
    case 'cron': {
      const trigger = {
        ...base,
        cron: form.cron.trim(),
        timezone: form.timezone.trim() || undefined,
      };
      return props.mode === 'create'
        ? { mode: 'create', trigger: trigger as TriggerSpecCreate }
        : { mode: 'edit', trigger: trigger as TriggerSpec };
    }
    case 'command': {
      const trigger = { ...base, commandKey: form.commandKey.trim() };
      return props.mode === 'create'
        ? { mode: 'create', trigger: trigger as TriggerSpecCreate }
        : { mode: 'edit', trigger: trigger as TriggerSpec };
    }
    case 'contextMenu': {
      const contexts = [...new Set(form.contextMenuContexts)].filter(Boolean);
      const trigger = { ...base, title: form.contextMenuTitle.trim(), contexts };
      return props.mode === 'create'
        ? { mode: 'create', trigger: trigger as TriggerSpecCreate }
        : { mode: 'edit', trigger: trigger as TriggerSpec };
    }
    case 'dom': {
      const trigger = {
        ...base,
        selector: form.domSelector.trim(),
        appear: !!form.domAppear,
        once: !!form.domOnce,
        debounceMs: Math.max(0, Math.floor(form.domDebounceMs)),
      };
      return props.mode === 'create'
        ? { mode: 'create', trigger: trigger as TriggerSpecCreate }
        : { mode: 'edit', trigger: trigger as TriggerSpec };
    }
    default:
      return props.mode === 'create'
        ? { mode: 'create', trigger: base as TriggerSpecCreate }
        : { mode: 'edit', trigger: base as TriggerSpec };
  }
}

function submit(): void {
  localError.value = null;
  if (isNodeManaged.value) return;
  if (!canSubmit.value) return;

  const payload = buildTrigger();
  if (localError.value) return;
  emit('submit', payload);
}
</script>

<style scoped>
.tr-modal-overlay {
  position: fixed;
  inset: 0;
  background: rgba(0, 0, 0, 0.42);
  display: flex;
  align-items: flex-start;
  justify-content: center;
  padding: 24px 12px;
  z-index: 1000;
}

.tr-modal {
  width: 100%;
  max-width: 520px;
  border-radius: 12px;
  background: var(--ac-surface, #ffffff);
  border: 1px solid var(--ac-border, #e5e5e5);
  box-shadow: 0 18px 60px rgba(0, 0, 0, 0.24);
  overflow: hidden;
}

.tr-modal-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  padding: 12px 14px;
  border-bottom: 1px solid var(--ac-border, #e5e5e5);
}

.tr-modal-title {
  font-size: 14px;
  font-weight: 600;
  color: var(--ac-text, #111827);
}

.tr-icon-btn {
  border: 0;
  background: transparent;
  color: var(--ac-text-muted, #6b7280);
  padding: 6px;
  border-radius: 8px;
  cursor: pointer;
}

.tr-icon-btn:hover {
  background: var(--ac-hover-bg, #f3f4f6);
  color: var(--ac-text, #111827);
}

.tr-modal-body {
  padding: 14px;
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.tr-modal-footer {
  display: flex;
  justify-content: flex-end;
  gap: 10px;
  padding: 12px 14px;
  border-top: 1px solid var(--ac-border, #e5e5e5);
  background: var(--ac-surface, #ffffff);
}

.tr-alert {
  border-radius: 10px;
  padding: 10px 12px;
  border: 1px solid var(--ac-border, #e5e5e5);
  background: var(--ac-surface-muted, #f8fafc);
  color: var(--ac-text, #111827);
}

.tr-alert-danger {
  border-color: rgba(239, 68, 68, 0.35);
  background: rgba(239, 68, 68, 0.08);
  color: var(--ac-danger, #ef4444);
}

.tr-alert-warn {
  border-color: rgba(245, 158, 11, 0.35);
  background: rgba(245, 158, 11, 0.08);
  color: var(--ac-text, #111827);
}

.tr-alert-title {
  font-weight: 600;
  margin-bottom: 2px;
}

.tr-alert-text {
  font-size: 12px;
  color: var(--ac-text-muted, #6b7280);
  margin-bottom: 10px;
}

.tr-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 12px;
}

.tr-field {
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.tr-field-inline {
  flex-direction: row;
  align-items: center;
}

.tr-label {
  font-size: 12px;
  color: var(--ac-text-muted, #6b7280);
  font-weight: 600;
}

.tr-label-spaced {
  margin-top: 6px;
}

.tr-input,
.tr-select,
.tr-textarea {
  width: 100%;
  border: 1px solid var(--ac-border, #e5e5e5);
  border-radius: 10px;
  padding: 9px 10px;
  font-size: 13px;
  background: var(--ac-surface, #ffffff);
  color: var(--ac-text, #111827);
}

.tr-textarea {
  font-family: var(
    --ac-font-mono,
    ui-monospace,
    SFMono-Regular,
    Menlo,
    Monaco,
    Consolas,
    monospace
  );
  font-size: 12px;
}

.tr-input:disabled,
.tr-select:disabled,
.tr-textarea:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

.tr-select-sm {
  padding: 7px 8px;
  border-radius: 9px;
  font-size: 12px;
}

.tr-input-sm {
  padding: 7px 8px;
  border-radius: 9px;
  font-size: 12px;
}

.tr-hint {
  font-size: 11px;
  color: var(--ac-text-subtle, #9ca3af);
  line-height: 1.25;
}

.tr-list {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.tr-list-row {
  display: grid;
  grid-template-columns: 150px 1fr auto auto auto;
  gap: 8px;
  align-items: center;
}

.tr-checkbox-grid {
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: 8px;
}

.tr-checkbox {
  display: flex;
  gap: 8px;
  align-items: center;
  font-size: 12px;
  color: var(--ac-text, #111827);
}

.tr-checkbox-input {
  width: 14px;
  height: 14px;
}

.tr-btn {
  border-radius: 10px;
  padding: 9px 12px;
  font-size: 13px;
  border: 1px solid var(--ac-border, #e5e5e5);
  background: var(--ac-surface, #ffffff);
  color: var(--ac-text, #111827);
  cursor: pointer;
}

.tr-btn:hover {
  background: var(--ac-hover-bg, #f3f4f6);
}

.tr-btn:disabled {
  opacity: 0.55;
  cursor: not-allowed;
}

.tr-btn-primary {
  border-color: rgba(59, 130, 246, 0.45);
  background: var(--ac-primary, #3b82f6);
  color: #fff;
}

.tr-btn-primary:hover {
  background: var(--ac-primary-strong, #2563eb);
}

.tr-btn-ghost {
  background: transparent;
}

.tr-btn-icon {
  padding: 6px 8px;
  border-radius: 9px;
  font-size: 12px;
}

.tr-btn-danger {
  border-color: rgba(239, 68, 68, 0.35);
  color: var(--ac-danger, #ef4444);
}

@media (max-width: 480px) {
  .tr-grid {
    grid-template-columns: 1fr;
  }
  .tr-list-row {
    grid-template-columns: 1fr;
  }
  .tr-checkbox-grid {
    grid-template-columns: repeat(2, minmax(0, 1fr));
  }
}
</style>
